### ISSUE TITLE
Open Source but i need licence?

### ISSUE THREAD

**Issue by PatchRequest** [Stuyk/altv-athena#10]
Is it correct that this project is "fully" opensource but i cant use it without the codesnipped from the chargeable Api?

**Comment by Stuyk** [comment]
That is correct. You're paying for more than just the code source itself.

You're paying for the ability to use it without restrictions.

**Comment by PatchRequest** [comment]
"You're paying for the ability to use it without restrictions."
I can´t start the server, so the restriction is that i can´t use it? or is there a demo version?

**Comment by falkebo** [comment]
@Stuyk then its not OS.
Open Source doesnt mean "Hey, get the Source Code, but you cant use it without paying."

**Comment by Stuyk** [comment]
> @Stuyk then its not OS.
> Open Source doesnt mean "Hey, get the Source Code, but you cant use it without paying."

I beg to differ on this comment solely because there are multiple ways you can boot this software. 
I'm not going to tell you how to do it because it's against my interests.
Thousands of companies don't provide support or documentation for their open-source projects for free.
They ask for a price for their documentation or knowledge. 
This is not uncommon in open source communities.

https://en.wikipedia.org/wiki/Business_models_for_open-source_software#Selling_optional_proprietary_extensions

So don't call it what it isn't because it is open-source software that anyone can utilize.
Granted that `anyone` is someone who knows their way around an alt:V Script. 
The knowledge is all out there for you to utilize but you must interpret how to start it yourself.

Also why wouldn't I want to get paid for providing knowledge that I've personally obtained by practicing writing code, creating algorithms, and designing architecture? That's absurd.

You get more than just `some open source code` from this repository. You get an entire framework that is carefully crafted from years of doing open source work for various GTA:V clients. You get all the designs that fix common issues other programmers run into for practically free.

You wouldn't want to pay the full price I would charge for a private version of this.

**Comment by PatchRequest** [comment]
So i can fork this project and make an version without the licence check?

**Comment by LeonMrBonnie** [comment]
Even if you have to pay to use it, it is completely free to use this as a learning resource and as a reference.
You should be grateful that this is even open source, but instead you came here to complain; And this is the reason that you have to pay for this, because people are ungrateful and don't appreciate someone else's work like they should.

**Comment by etlon** [comment]
But this is trash as open source

**Comment by LeonMrBonnie** [comment]
> 
> 
> But this is trash as open source

Then don't use it and fuck off.

**Comment by etlon** [comment]
mad cause bad?

**Comment by Stuyk** [comment]
> But this is trash as open source

Let me know when you release your open source script and I'll come to check it out.
